apiVersion: v1 
kind: Pod 
metadata: 
  name: my-app
  labels:
    tier: frontend
spec: 
  containers:
  - name: nginx
    image: nginx
    containerPorts:
      port: 80
    resources:
      requests:
        memory: "10Mi"
        cpu: "50m"
      limits: 
        memory: "30Mi"
        cpu: "70m"
# kubectl taint node node1 allowTier=frontend:NoSchedule
  tolerations:
  -  key: "allowTier"
     operator: "Equals"
     value: "frontend"
     effect: "NoSchedule"