apiVersion: v1
kind: Pod 
metadata:
  name: hive-pod
spec:
  containers:
    - name: trino
      image: nginx
      resources: {}
      volumeMounts:
        - mountPath: /etc/trino/gcs.json
          subPath: gcs.json
          name: gcs-volume
  volumes:
    - name: gcs-volume
      configMap:
        name: myapp-config