apiVersion: v1 
kind: Pod 
metadata: 
  name: my-app-data-processor
  labels:
    tier: frontend
spec: 
  containers:
  - name: data-processor
    image: data-processor
    containerPorts:
      port: 80
    resources:
      requests:
        memory: "10Mi"
        cpu: "50m"
      limits: 
        memory: "30Mi"
        cpu: "70m"
# kubectl label nodes node01 key=value
  nodeSelector:
    size: "large"